### ISSUE TITLE
Issues with SST deployment

### ISSUE THREAD

**Issue by gersongams** [getcronit/pylon#23]
**Describe the bug**
I want to deploy the app using SST, I'm running `npx sst dev` and when I tried to make any /graphql request is returning a 404

**To Reproduce**
I've tried with my `src/index.ts`
```typescript
import { app } from '@getcronit/pylon'
import { handle } from "hono/aws-lambda";

export const graphql = {
  Query: {
    hello: () => {
      return 'Hello, world! x2'
    }
  },
  Mutation: {}
}

app.get("/health", (ctx, next) => {
  return new Response("OK!");
});

export const handler = handle(app)
export default app
```

with SST config

```typescript
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: "store-backend",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
    };
  },
  async run() {
    const hono = new sst.aws.Function("StoreBackend", {
      url: true,
      handler: "src/index.handler",
    });

    return {
      api: hono.url,
    };
  },
});
```

The app runs well locally but trying to access the `/graphql` endpoint in the deployed version from SST, the endpoint `/health` works but trying to make any `POST` request to `/graphql` fails

**Expected behavior**
it should return 
```
{
  "data": {
    "hello": "Hello, world! x2"
  }
}
```

**Screenshots**

I changed the URL of the endpoint
![image](https://github.com/user-attachments/assets/152c32fd-b5e6-4444-a806-796fc5e8b2dc)
![image](https://github.com/user-attachments/assets/e024a9ee-8005-4d33-bd67-f9619e6da557)
![image](https://github.com/user-attachments/assets/2c488532-5f1d-4f60-968a-032f595eccd3)

**Comment by schettn** [comment]
Hi @gersongams!

I will take a deeper look into that tomorrow.

Some quick thoughts on this topic:

1. You need to run `npm pylon build`. This generates the `.pylon/index.js` file. This happens automatically in development, but should be defined in your build step.
2. Instead of referencing the `src/index.handler` in your SST config, use `.pylon/index.js`

Please let me know if this works for you.

**Comment by gersongams** [comment]
thank you @schettn !!!! You are the best

**Comment by schettn** [comment]
Glad it works @gersongams!

I want to include AWS as a Pylon template in the future. Before that I need to do some research because I am not familiar with AWS that much. Don’t even have an account there yet.
