### ISSUE TITLE
Support Env Augmentation 

### ISSUE THREAD

**Issue by yavuzselim8** [getcronit/pylon#25]
**Is your feature request related to a problem? Please describe.**
Hello, thank you for creating this library it looks perfect, I have been looking at it since yesterday and experimenting. I have one question:

As far as I understand from the documentation, we are encouraged to use the Hono instance for custom middlewares and endpoints. In one of my middleware, I am trying to set some dataloaders in context to use them later. I am having a problem here with the typescript not allowing me to set a variable. I tried module augmentation but since Env is a type, not an interface that option is not viable right now. Do you guys have any suggestions? BTW, this is not just related to dataloaders I happened to try that first. Thank you in advance 🙏

Here is the screenshot of the TS error

<img width="782" alt="Screenshot_2024-10-01_at_15 13 07" src="https://github.com/user-attachments/assets/5c78ec74-8a8c-4577-a64a-8614a45f2a9a">

**Describe the solution you'd like**
Env can be changed to interface to allow augmentation

**Comment by schettn** [comment]
You can now add a file called `pylon.d.ts`:
```ts
import '@getcronit/pylon'

declare module '@getcronit/pylon' {
  interface Bindings {
    DB: D1Database
  }

  interface Variables {}
}
```

And add it to the `tsconfig.json`:
```json
{
  "extends": "@getcronit/pylon/tsconfig.pylon.json",
  "include": ["pylon.d.ts", "src/**/*.ts"]
}
```

ref: https://github.com/getcronit/pylon/tree/main/examples/cloudflare-drizzle-d1

This is available on `@getcronit/pylon-v2.1.1` and `create-pylon-v1.0.3`
