### ISSUE TITLE
Unhandled Exception Causes Restart Requirement

### ISSUE THREAD

**Issue by jaemig** [getcronit/pylon#3]
**Describe the bug**
An unhandled exception causes the process to exit with code 1, requiring a manual restart of the pylon server.

**To Reproduce**
1. Go to `src/index.ts`
2. Explicitly throw an error

**Expected behavior**
The process should handle the exception gracefully and provide a clear error message without requiring a manual restart. Ideally, the development server should continue running, allowing the developer to fix the issue and retry without restarting the entire process.

**Screenshots**
![Screenshot 2024-07-24 at 23 11 54](https://github.com/user-attachments/assets/1ecf6c87-86ff-438e-929a-4f2363d71db5)

**Desktop:**
 - OS: MacOS Sonoma 14.5

**Comment by schettn** [comment]
Thanks for the issue!

I agree, this will be fixed during this week.
