### ISSUE TITLE
Feat: Access to the info object (graphqlResolveInfo)

### ISSUE THREAD

**Issue by LowLifeArcade** [getcronit/pylon#59]
The graphQL info object will help make more consice database queries depending on the graphQL query.

### Requirements:
- Access to the info object an idiomatic Pylon way (currently being implemented through context)
- @schettn to add details

NOTES:
Current work will be exposing this through the hono context for users to create helper methods on top of.

Relates to [Resolver Chains discussion](https://github.com/getcronit/pylon/issues/58)

**Comment by schettn** [comment]
See: [Example Usage](https://github.com/getcronit/pylon/tree/main/examples/graphql-resolve-info)
